// src/pages/VerifyMLAlerts.jsx
import React from 'react';

const alerts = [
  { id: 1, alert: 'Flood warning', prediction: 'High', status: 'Accepted' },
  { id: 2, alert: 'Earthquake detected', prediction: 'Medium', status: 'Rejected' },
  { id: 3, alert: 'Tornado alert', prediction: 'Low', status: 'Accepted' },
  // Add more alert data as needed
];

const VerifyMLAlerts = () => {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center p-4">
      <div className="w-full max-w-4xl p-6 bg-white shadow-lg rounded-lg">
        <h1 className="text-2xl font-bold text-gray-800 mb-4">Verify Machine Learning Alerts</h1>
        <p className="text-gray-600 mb-4">
          This page displays and manages machine learning alerts. Review the alerts generated by the ML models below.
        </p>
        <div className="border-t border-gray-200 pt-4">
          <h2 className="text-xl font-semibold text-gray-700 mb-2">Alerts Overview</h2>
          <table className="w-full bg-white border border-gray-200 rounded-lg shadow-sm">
            <thead>
              <tr className="bg-gray-100 border-b">
                <th className="p-4 text-left text-gray-600">Alert</th>
                <th className="p-4 text-left text-gray-600">Prediction</th>
                <th className="p-4 text-left text-gray-600">Status</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map((alert) => (
                <tr key={alert.id} className="border-b">
                  <td className="p-4 text-gray-700">{alert.alert}</td>
                  <td className="p-4 text-gray-700">{alert.prediction}</td>
                  <td className={`p-4 font-semibold ${alert.status === 'Accepted' ? 'text-green-600' : 'text-red-600'}`}>
                    {alert.status}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default VerifyMLAlerts;
